In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [93]:
df = pd.read_csv('NCD_RisC_Nature_2020_Cholesterol_age_specific_countries_sql.csv').reset_index(drop = True)
#df

In [94]:
%load_ext sql
%config SqlMagic.autopandas = True  # Automatically convert query results to pandas dataframes
%sql duckdb://

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [95]:
df.columns

Index(['Country', 'Year', 'Gender', 'Age_group',
       'Mean_total_cholesterol_mmolL',
       'Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
       'Mean_non_HDL_cholesterol_mmolL',
       'Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
       'Mean_HDL_cholesterol_mmolL',
       'Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL'],
      dtype='object')

In [96]:
%%sql
drop table if exists temp_a;
create table temp_a
as select * 
from 'NCD_RisC_Nature_2020_Cholesterol_age_specific_countries_sql.csv'

Running query in 'duckdb://'

Empty DataFrame
Columns: [Success]
Index: []

In [97]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Country
from temp_a;
select distinct Country from temp_b

Running query in 'duckdb://'

            Country
0     Cote d'Ivoire
1           Denmark
2           Hungary
3            Kuwait
4         Nicaragua
..              ...
195          Greece
196   Guinea Bissau
197            Iraq
198        Zimbabwe
199  American Samoa

[200 rows x 1 columns]

In [98]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Year
from temp_a;
select distinct Year from temp_b

Running query in 'duckdb://'

    Year
0   1995
1   2002
2   2011
3   2012
4   1985
5   1989
6   1994
7   1997
8   2010
9   1983
10  1986
11  2018
12  1984
13  2003
14  2004
15  2013
16  1992
17  2000
18  2016
19  1988
20  1993
21  1999
22  2015
23  2017
24  1987
25  2007
26  1990
27  1998
28  2009
29  2014
30  1982
31  2008
32  1991
33  1996
34  2006
35  1980
36  2001
37  2005
38  1981

In [99]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Gender
from temp_a;
select distinct Gender from temp_b

Running query in 'duckdb://'

  Gender
0  Women
1    Men

In [100]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Age_group
from temp_a;
select distinct Age_group from temp_b

Running query in 'duckdb://'

   Age_group
0      18-19
1     85plus
2      55-59
3      30-34
4      35-39
5      40-44
6      45-49
7      80-84
8      60-64
9      25-29
10     20-24
11     50-54
12     65-69
13     75-79
14     70-74

In [101]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_total_cholesterol_mmolL
from temp_a;
select distinct Mean_total_cholesterol_mmolL from temp_b

Running query in 'duckdb://'

        Mean_total_cholesterol_mmolL
0                           4.376619
1                           4.344149
2                           4.411755
3                           4.257728
4                           4.414472
...                              ...
233995                      3.741001
233996                      3.737965
233997                      4.519984
233998                      4.466998
233999                      4.393009

[234000 rows x 1 columns]

In [102]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL
from temp_a;
select distinct Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL from temp_b

Running query in 'duckdb://'

        Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL
0                                                6.107196
1                                                6.347015
2                                                6.370414
3                                                6.284883
4                                                6.414438
...                                                   ...
233995                                           3.976934
233996                                           4.363172
233997                                           4.903548
233998                                           6.218327
233999                                           5.072861

[234000 rows x 1 columns]

In [103]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL
from temp_a;
select distinct Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL from temp_b

Running query in 'duckdb://'

        Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL
0                                                6.074373
1                                                6.649485
2                                                5.720063
3                                                6.957647
4                                                5.195639
...                                                   ...
233995                                           5.842674
233996                                           6.276266
233997                                           5.330676
233998                                           6.220084
233999                                           6.930979

[234000 rows x 1 columns]

In [104]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_non_HDL_cholesterol_mmolL
from temp_a;
select distinct Mean_non_HDL_cholesterol_mmolL from temp_b

Running query in 'duckdb://'

        Mean_non_HDL_cholesterol_mmolL
0                             4.141643
1                             4.611444
2                             5.258656
3                             3.958885
4                             4.920823
...                                ...
233995                        2.967813
233996                        3.523520
233997                        3.652244
233998                        5.291427
233999                        5.287221

[234000 rows x 1 columns]

In [105]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL
from temp_a;
select distinct Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL from temp_b

Running query in 'duckdb://'

        Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL
0                                                3.932768
1                                                3.582617
2                                                3.911653
3                                                4.531422
4                                                4.810760
...                                                   ...
233995                                           2.885232
233996                                           3.516104
233997                                           3.370816
233998                                           2.760382
233999                                           4.929688

[234000 rows x 1 columns]

In [106]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL
from temp_a;
select distinct Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL from temp_b

Running query in 'duckdb://'

        Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL
0                                                3.117520
1                                                3.399162
2                                                3.719245
3                                                3.620660
4                                                3.030430
...                                                   ...
233995                                           2.992894
233996                                           4.144434
233997                                           3.110601
233998                                           3.601362
233999                                           3.511585

[234000 rows x 1 columns]

In [107]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_HDL_cholesterol_mmolL
from temp_a;
select distinct Mean_HDL_cholesterol_mmolL from temp_b

Running query in 'duckdb://'

        Mean_HDL_cholesterol_mmolL
0                         1.207433
1                         1.282841
2                         1.220993
3                         1.241760
4                         1.258649
...                            ...
233995                    1.316188
233996                    1.399253
233997                    1.264621
233998                    1.326474
233999                    1.448101

[234000 rows x 1 columns]

In [108]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL
from temp_a;
select distinct Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL from temp_b

Running query in 'duckdb://'

        Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL
0                                                1.471008
1                                                1.448285
2                                                1.228181
3                                                1.302284
4                                                1.235395
...                                                   ...
233995                                           1.530399
233996                                           1.539615
233997                                           1.457851
233998                                           1.503419
233999                                           1.346575

[234000 rows x 1 columns]

In [109]:
%%sql
drop table if exists temp_b;
create table temp_b
as select Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL
from temp_a;
select distinct Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL from temp_b

Running query in 'duckdb://'

        Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL
0                                                1.772359
1                                                1.753710
2                                                1.753904
3                                                1.691240
4                                                1.764865
...                                                   ...
233995                                           1.784345
233996                                           1.794658
233997                                           1.795013
233998                                           1.712389
233999                                           1.831970

[234000 rows x 1 columns]